function [ x_best, y_best, z_best, rerr, it_cnt ] = Nav_toa_hjs_3d_solve(base_points, x_prev, y_prev, z_prev,...
    max_iterations, precision_threshold, step_size)
    [ x_best, y_best, z_best, rerr, it_cnt ] = Nav_hjs_3d_solve(@Nav_eps_toa3d, base_points, x_prev, y_prev, z_prev,...
        max_iterations, precision_threshold, step_size);
end