function [ x_best, y_best, z_best, rerr, it_cnt ] = Nav_tdoa_nlm_3d_solve(base_lines, x_prev, y_prev, z_prev,...
    max_iterations, precision_threshold, simplex_size)
    [ x_best, y_best, z_best, rerr, it_cnt ] = Nav_nlm_3d_solve(@Nav_eps_tdoa3d, base_lines, x_prev, y_prev, z_prev,...
        max_iterations, precision_threshold, simplex_size);
end